 include vcontex.inc

;
;
;
extrn init_vid:near
extrn kill_vid:near
extrn printChar:near
extrn printHexNibble:near
extrn printHexByte:near
extrn printHexWord:near
extrn printHexDWord:near
extrn println:near
extrn print_size:near
extrn showZero:near
extrn GetChar:near
extrn GetLine:near
extrn GetNextParam:near
extrn ascii2hex:near
extrn displayBuffer:near
extrn gwDrives:near
extrn vidcontext:near
extrn activeWindow:near
extrn init_command:near
extrn init_sector:near