;*****************************************************************************
;  vgutl - video utility routines
;       Copyright 2005 Greg Honsa
;
;*****************************************************************************
						    
extrn vgaSetPalette:near
extrn vbeGetMode:near							 
extrn vbeSetMode:near
extrn vbeGetInfo:near
extrn vbeGetModeInfo:near
extrn vbeSetBankAddr:near
extrn vbeSetDisplayStart:near	 
extrn waitBlankEnd:near
extrn waitRetrace:near
extrn memset:near






						   
					   